# Generated by Django 2.2.7 on 2021-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Boat_identification_number', models.TextField(blank=True)),
                ('make', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('price_per_person', models.IntegerField()),
                ('location', models.TextField(blank=True)),
            ],
        ),
    ]
