# Generated by Django 2.2.7 on 2021-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
