# Generated by Django 2.2.7 on 2021-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_boat_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('date_of_birth', models.TextField(blank=True)),
            ],
        ),
    ]
