# Generated by Django 2.2.7 on 2021-04-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('date_of_birth', models.TextField(blank=True)),
                ('years_of_experience', models.IntegerField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
