# Generated by Django 2.2.7 on 2021-04-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
