# Generated by Django 2.2.7 on 2021-04-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210415_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='Location_description',
            field=models.TextField(blank=True),
        ),
    ]
