# Generated by Django 2.2.7 on 2021-04-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210428_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='location_image_url',
            field=models.URLField(blank=True),
        ),
    ]
