# Generated by Django 2.2.7 on 2021-04-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_boat_location_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
