# Generated by Django 2.2.7 on 2021-03-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('email_address', models.TextField(blank=True)),
                ('imgage_url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='facebook',
        ),
    ]
