# Generated by Django 2.2.7 on 2021-03-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_auto_20210318_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imgage_url',
            new_name='image_url',
        ),
    ]
