# Generated by Django 2.2.7 on 2021-03-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_statusmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
